on:
  push: {}
  schedule:
    - cron: 0/5 * * * *
  workflow_dispatch:
    inputs:
      check:
        required: false
        type: boolean
        default: false
        description: "check that everything is published correctly"
env:
  CHECK: ${{ inputs.check || false }}
  FOO: toJSON({a: "b", b :${{inputs.check}} })
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I'm running $FOO"
