on:
  push: {}
  schedule:
    - cron: 0/5 * * * *
  workflow_dispatch:
    inputs:
      check:
        required: false
        type: boolean
        default: false
        description: "check that everything is published correctly"
      arch:
        required: false
        default: "amd64"
      runs-on:
        required: false
      githubRunnersByArch:
        required: false
        default: '{"amd64": "ubuntu-latest"}'
env:
  CHECK: ${{ inputs.check || false }}
  ARCH: ${{ inputs.arch || 'amd64' }}
  FOO: ${{ fromJSON(vars.NOT_EXIST || 10)

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ toJSON(env) }}
    steps:
      - id: set-env
        run: |
          echo hello
          echo ${{ env.FOO }}
          echo ${{ fromJSON(vars.NOT_A_THING || 10) }}
          echo ${{ fromJSON(vars.NO_GOOD ) }}
  other:
    needs: [check]
    uses: ./.github/workflows/wfc_test.yaml
    with:
      foo: bar
      env: ${{ needs.check.outputs.env }}
  numCPU:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - run: go run test.go
