name: test
on:
  workflow_dispatch

jobs:
  jqtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: "../other-path"
      - name: complex yq
        working-directory: "../other-path"
        run: make check
      - uses: actions/checkout@v3
      - name: complex yq
        run: make check
