on:
  push: {}
  schedule:
    - cron: 0/5 * * * *
  workflow_dispatch:
    inputs:
      check:
        required: false
        type: boolean
        default: false
        description: "check that everything is published correctly"
      arch:
        required: false
        default: "amd64"
      runs-on:
        required: false
      githubRunnersByArch:
        required: false
        default: '{"amd64": "ubuntu-latest"}'
env:
  CHECK: ${{ inputs.check || false }}
  ARCH: ${{ inputs.arch || 'amd64' }}
  RUNS_ON_CIRCLECI: ${{ fromJSON(inputs.githubRunnersByArch)[inputs.arch] == '' }}
  RUNS_ON_GITHUB: ${{ fromJSON(inputs.githubRunnersByArch)[inputs.arch] != '' }}

jobs:
  example:
    runs-on: ${{ inputs.runs-on || vars.RUNS_ON || 'ubuntu-latest' }}
    steps:
      - run: echo "I'm running ${{ env.RUNS_ON_CIRCLECI }} ${{ env.RUNS_ON_GITHUB }} ${{ github.runner }}"
      - run: echo "inputs ${{ toJSON(inputs) }}"
  other:
    uses: ./.github/workflows/wfc_test.yaml
    with:
      foo: bar
