name: project-lifecycle
on:
  workflow_dispatch

jobs:
  jqtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: complex jq 
        uses: mikefarah/yq@master
        with:
          cmd: make check
