on:
  push: {}
  schedule:
    - cron: 0/5 * * * *
  workflow_dispatch:
    inputs:
      check:
        required: false
        type: boolean
        default: false
        description: "check that everything is published correctly"
      arch:
        required: false
        default: "amd64"
      runs-on:
        required: false
      githubRunnersByArch:
        required: false
        default: '{"amd64": "ubuntu-latest"}'
env:
  CHECK: ${{ inputs.check || false }}
  ARCH: ${{ inputs.arch || 'amd64' }}
  FOO: "hello"

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ fromJSON(env) }}
    steps:
      - id: set-env
        run: |
          echo hello
  other:
    needs: [check]
    uses: ./.github/workflows/wfc_test.yaml
    with:
      foo: bar
      env: ${{ needs.check.outputs.env }}
