name: test 
on:
  workflow_dispatch

jobs:
  jqtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install-jq
        run: sudo apt-get install jq
      - name: complex jq 
        run: make check
