on:
  schedule:
    - cron: 5,10,15,20,25,30,35,40,45 * * * *
  workflow_dispatch:
    inputs:
      check:
        required: false
        type: boolean
        default: false
        description: "check that everything is published correctly"
env:
  CHECK: ${{ inputs.check || false }}
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - if: fromJSON(env.CHECK)
        run: echo "I'm running"
