on:
  push: {}
  schedule:
    - cron: 0/5 * * * *
  workflow_dispatch:
    inputs:
      check:
        required: false
        type: boolean
        default: false
        description: "check that everything is published correctly"
      arch:
        required: false
        default: "amd64"
env:
  CHECK: ${{ inputs.check || false }}
  ARCH: ${{ inputs.arch || 'amd64' }}
  GITHUB_RUNNERS_BY_ARCH: '{"amd64": "ubuntu-latest"}'
  RUNS_ON_CIRCLECI: ${{ !(fromJSON(github.env.GITHUB_RUNNERS_BY_ARCH)[github.env.ARCH]) }}
  RUNS_ON_GITHUB: ${{ !(fromJSON(github.env.GITHUB_RUNNERS_BY_ARCH)[github.env.ARCH]) }}
  RUNNER: ${{ fromJSON(github.env.GITHUB_RUNNERS_BY_ARCH)[github.env.ARCH] || 'ubuntu-latest' }}

jobs:
  example:
    runs-on: ${{ env.RUNNER }} 
    steps:
      - run: echo "I'm running ${{ env.RUNS_ON_CIRCLECI }} ${{ env.RUNS_ON_GITHUB }} ${{ env.RUNNER }}"
