on:
  schedule:
    - cron: 0/5 * * * *
  workflow_dispatch:
    inputs:
      check:
        required: false
        type: boolean
        default: false
        description: "check that everything is published correctly"
env:
  CHECK: ${{ inputs.check == "true" }}
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ env.CHECK }}"
      - if: fromJSON(env.CHECK)
        run: echo "I'm running"
