on:
  workflow_call:
    inputs:
      foo:
        type: string
        required: true
      env:
        type: string
        required: true
env:
  PARAM: ${{ inputs.foo }}

jobs:
  test_env:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.env }} >> $GITHUB_ENV
      - run: env 
  bar:
    needs: [test_env]
    steps:
      - run: env
