on:
  workflow_call:
    inputs:
      foo:
        type: string
        required: true
env:
  PARAM: ${{ inputs.foo }}

jobs:
  test_env:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: ${{ env.ARCH }}
