on:
  workflow_call:
    inputs:
      foo:
        type: string
        required: true
      env:
        type: string
        required: true
env:
  PARAM: ${{ inputs.foo }}

jobs:
  test_env:
    runs-on: ubuntu-latest
    steps:
      - run: |
          for i in $( echo "${{ inputs.env }}" | jq -r 'to_entries | .[] | .key + "=" + (.value | tostring)'); do
            echo ${i} >> $GITHUB_ENV
          done
      - run: env
  bar:
    runs-on: ubuntu-latest
    needs: [test_env]
    steps:
      - run: env
